DROP TABLE IF EXISTS CHAT_USERS;
CREATE TABLE CHAT_USERS (ID INTEGER PRIMARY KEY  AUTOINCREMENT  NOT NULL  UNIQUE , NICKNAME VARCHAR(20) NOT NULL  UNIQUE , EMAIL VARCHAR(20) NOT NULL  UNIQUE , PASS VARCHAR(15) NOT NULL )
